#!/usr/bin/env bash

set -euo pipefail

curl_version="8.5.0-2ubuntu10.9"
ca_certificates_version="20240203"
gnupg_version="2.4.4-2ubuntu17.4"
kubelet_version="1.36.1-1.1"
kubeadm_version="1.36.1-1.1"
kubectl_version="1.36.1-1.1"
containerd_io_version="2.2.4-1~ubuntu.24.04~noble"

echo "INFO: Starting to install dependencies..."
apt update
apt install -y \
	curl="${curl_version}" \
	ca-certificates="${ca_certificates_version}" \
	gnupg="${gnupg_version}"

echo "INFO: Adding Docker GPG key and repository ..."
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
	-o /etc/apt/keyrings/docker.asc
chmod 0444 /etc/apt/keyrings/docker.asc

# shellcheck disable=SC1091
tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF

echo "INFO: Adding kubernetes key and repository ..."
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key |
	gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /' |
	tee /etc/apt/sources.list.d/kubernetes.list

echo "Installing AMI dependencies"
apt update
apt install -y \
	containerd.io="${containerd_io_version}" \
	kubelet="${kubelet_version}" \
	kubeadm="${kubeadm_version}" \
	kubectl="${kubectl_version}"

apt-mark hold kubelet kubeadm kubectl

echo "INFO: Enable kubelet"
systemctl enable --now kubelet
