#!/usr/bin/env bash
#
# Swap: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# Ipv4: https://kubernetes.io/docs/setup/production-environment/container-runtimes/

set -euo pipefail

echo "INFO: Disabling swap..."
swapoff -a
sed -i '/\sswap\s/d' /etc/fstab

echo "INFO: Enable IPv4 packet forwarding..."
tee /etc/sysctl.d/k8s.conf <<EOF
net.ipv4.ip_forward = 1
EOF

sysctl --system

if [ "$(sysctl net.ipv4.ip_forward)" -ne 1 ]; then
	echo "ERROR: IPv4 forwarding is disabled."
	exit 1
fi
echo "SUCCESS: Finished node preparation."
