stages:
  - build
  - lint
  - test
  - security
variables:
  DEV_IMAGE: $CI_REGISTRY_IMAGE/dev:$CI_COMMIT_SHORT_SHA
  DEV_IMAGE_LATEST: $CI_REGISTRY_IMAGE/dev:latest
include:
  - local: .gitlab/ci/build-jobs/dev-image.yaml
  - local: .gitlab/ci/lint-jobs/lint.yaml
  - local: .gitlab/ci/lint-jobs/openapi.yaml
  - local: .gitlab/ci/test-jobs/base.yaml
  - local: .gitlab/ci/test-jobs/registration.yaml
  - local: .gitlab/ci/test-jobs/task.yaml
  - local: .gitlab/ci/test-jobs/tms_auth.yaml
  - local: .gitlab/ci/test-jobs/user.yaml
  - local: .gitlab/ci/test-jobs/task_management_system.yaml
  - local: .gitlab/ci/security-jobs/security.yaml
