stages:
  - build
  - lint

variables:
  DEV_IMAGE: $CI_REGISTRY_IMAGE/dev:$CI_COMMIT_SHORT_SHA
  DEV_IMAGE_LATEST: $CI_REGISTRY_IMAGE/dev:latest

include:
  - local: .gitlab/ci/build-jobs/dev-image.yaml
  - local: .gitlab/ci/lint-jobs/lint.yaml
