stages:
  - build
  - lint

variables:
  DEV_IMAGE: $CI_REGISTRY_IMAGE/dev:$CI_COMMIT_SHORT_SHA
  DEV_IMAGE_LATEST: $CI_REGISTRY_IMAGE/dev:latest

include:
  - local: .gitlab/ci/build-jobs/dev-image.yaml

lint:
  stage: lint
  image: $DEV_IMAGE_LATEST
  needs:
    - build-dev-image
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.pre-commit-cache
  cache:
    paths:
      - .pre-commit-cache/
  script:
    - pre-commit run --all-files
