#!/usr/bin/env bash

set -euo pipefail

echo "INFO: Starting to initialized directory structure."

keyring="/etc/apt/keyrings/"
mkdir -p "${keyring}"
sudo chmod 0755 "${keyring}"
echo "INFO: Created keyring diretory '${keyring}'."

source_list_d="/etc/apt/sources.list.d"

mkdir -p "${source_list_d}"
sudo chmod 0755 "${source_list_d}"
echo "INFO: Created directory for sources '${source_list_d}'."

echo "SUCCESS: Initialized directory structure"
