# Generated by Django 5.1.7 on 2026-05-18 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="members",
            field=models.ManyToManyField(
                related_name="tasks",
                through="task.TaskMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasknote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasknote",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="task.task",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "task"), name="unique_user_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner")),
                fields=("task",),
                name="unique_task_owner",
            ),
        ),
    ]
