FROM nginx:stable-alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/dev.conf /etc/nginx/conf.d/default.conf
COPY certs/local.key /etc/nginx/certs/local.key
COPY certs/local.crt /etc/nginx/certs/local.crt

EXPOSE 80 443
