apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery-worker
  namespace: {{ .Values.environment }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celery_worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-celery-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-celery-worker
    spec:
      containers:
        - name: celery-worker
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["celery"]
          args: ["-A", "task_management_system", "worker", "-l", "info"  ,"--concurrency=2"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          livenessProbe:
            exec:
              command: ["celery", "-A", "task_management_system", "inspect", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            {{- toYaml .Values.celery_worker.resources | nindent 12 }}
