apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.environment }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Values.environment }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: SQL_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: SQL_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: SQL_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.db.user }}"]
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
  namespace: {{ .Values.environment }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: 5432
