apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.environment }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.api.django_secret_key | quote }}
  JWT_SECRET_KEY: {{ .Values.api.jwt_secret_key | quote }}
  EMAIL_HOST_USER: {{ .Values.api.email_host_user | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.api.email_host_password | quote }}
  SQL_USER: {{ .Values.db.user | quote }}
  SQL_PASSWORD: {{ .Values.db.password | quote }}
