environment: dev
api:
  image:
    respository: tasky
    tag: latest
    pullPolicy: Never
  replicas: 3
  port: 8000
db:
  engine: django.db.backends.postgresql
  name: postgres-dev
  host: db-dev
  port: postgres
  password: postgres # Will be ignore, just here for ci
  user: postgres # Will be ignore, just here for ci
