environment: dev
api:
  image:
    respository: tasky
    tag: latest
    pullPolicy: Never
  replicas: 3
  port: 8000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Env Vars
  django_settings_module: task_management_system.settings.development
  django_secret_key: ci-test-only-not-a-real-secret-padding-0123456789abcdeff15949523575005523abdea435fc80ae995b38d2a4afb
  django_allowed_hosts: localhost 127.0.0.1 [::1] 0.0.0.0
  jwt_secret_key: 4842c13ffa0fea63d8464589404c2f1838abf6534ecbd59e2c5eedc76d5f4f18
  email_host: sandbox.smtp.mailtrap.io
  email_port: 2525
  # Will be ignore, just here for ci (not needed only if you want to check email in dev)
  email_host_user: <your-mailtrap-user>
  email_host_password: <your-mailtrap-password>
db:
  engine: django.db.backends.postgresql
  name: postgres
  host: postgres
  port: 5432
  password: postgres # Will be ignore, just here for ci
  user: postgres # Will be ignore, just here for ci
