plugin: amazon.aws.aws_ec2
regions:
  - "{{ lookup('env', 'TF_VAR_AWS_REGION') }}"
filters:
  tag:Project: "{{ lookup('env', 'TF_VAR_PROJECT_NAME') }}"
  tag:Role: gitlab-runner
  tag:Environment: dev
compose:
  ansible_host: instance_id
