plugin: amazon.aws.aws_ec2
regions:
  - "{{ lookup('env', 'TF_VAR_aws_region') }}"
filters:
  tag:Project: "tasky"
  tag:Role: gitlab-runner
  tag:Environment: dev
compose:
  ansible_host: instance_id
