- name: Remove old versions
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: true
- name: Install docker install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: present
    update_cache: true
    lock_timeout: 600
