#!/usr/bin/env bash

set -euo pipefail

user="tasky"
group="tasky"

function test_non_root_user() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -u)
    if [ "${result}" -eq 0 ]; then
        echo "ERROR: UID is ${result}. This is the root user." && exit 1
    fi
    echo "PASSED: User is not root user."
}

function test_non_root_group() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -g)
    if [ "${result}" -eq 0 ]; then
        echo "ERROR: GID is ${result}. This is the root group." && exit 1
    fi
    echo "PASSED: Group is not root group."
}

function test_user_name() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -un)
    if [ "${result}" != "${user}" ]; then
        echo "ERROR: User is ${result}. This is not user '${user}'." && exit 1
    fi
    echo "PASSED: User is '${user}'."
}

function test_group_name() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -gn)
    if [ "${result}" != "${group}" ]; then
        echo "ERROR: Group is ${result}. This is not group '${group}'." && exit 1
    fi
    echo "PASSED: Group is '${group}'."
}


function main() {
    if [[ -z "${PROD_IMAGE}" ]]; then
        echo "ERROR: PROD_IMAGE is not defined." && exit 1
    fi
    test_non_root_user
    test_non_root_group
    test_user_name
    test_group_name
}

main
