#!/usr/bin/env bash

set -euo pipefail

user="tasky"
group="tasky"

function test_non_root_user() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -u)
    if [ "${result}" -eq 0 ]; then
        echo "ERROR: UID is ${result}. This is the root user." && exit 1
    fi
    echo "PASSED: User is not root user."
}

function test_non_root_group() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -g)
    if [ "${result}" -eq 0 ]; then
        echo "ERROR: GID is ${result}. This is the root group." && exit 1
    fi
    echo "PASSED: Group is not root group."
}

function test_user_name() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -un)
    if [ "${result}" != "${user}" ]; then
        echo "ERROR: User is ${result}. This is not user '${user}'." && exit 1
    fi
    echo "PASSED: User is '${user}'."
}

function test_group_name() {
    result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -gn)
    if [ "${result}" != "${group}" ]; then
        echo "ERROR: Group is ${result}. This is not group '${group}'." && exit 1
    fi
    echo "PASSED: Group is '${group}'."
}

function test_user_ownership() {
    result=$(docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'stat -c "%U" .')
    if [ "${result}" != "${user}" ]; then
        echo "ERROR: User '${user}' is not the ower of the working directory." && exit 1
    fi
    echo "PASSED: User '${user}' has ownership."
}

function test_group_ownership() {
    result=$(docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'stat -c "%G" .')
    if [ "${result}" != "${group}" ]; then
        echo "ERROR: Group '${group}' is not the ower of the working directory." && exit 1
    fi
    echo "PASSED: Group '${group}' has ownership."
}

function test_no_leaked_tool_from_stage_builder() {
    deps=("poetry" "gcc" 'make')
    for dep in "${deps[@]}"; do
        docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'command -v ${tool}'
        result=$?
        if [ "${result}" -eq 127 ]; then
            echo "ERROR: Command '${dep}' is leaked to main image. Exit code " && exit 1
        fi
    done
    echo "PASSED: No tool is leaked."
}

test_broken_pip_packages() {
    docker run --rm --entrypoint pip "${PROD_IMAGE}" check > /dev/null
    result=$?
    if [ "${result}" -ne 0 ]; then
        echo "ERROR: A Python requirement is broken. Exit code ${result}" >&2
        exit 1
    fi
    echo "PASSED: No broken requirements found."
}

function main() {
    if [[ -z "${PROD_IMAGE}" ]]; then
        echo "ERROR: PROD_IMAGE is not defined." && exit 1
    fi
    test_non_root_user
    test_non_root_group
    test_user_name
    test_group_name
    test_user_ownership
    test_group_ownership
    test_no_leaked_tool_from_stage_builder
    test_broken_pip_packages
}

main
