security:
  stage: security
  image: $DEV_IMAGE_LATEST
  tags:
    - dev
  needs:
    - test:task
    - test:registration
    - test:tms_auth
    - test:user
    - test:task_management_system
  script:
    - pip-audit
