- name: Install gitlab-runner dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: true
- name: Added gitlab-runner repo
  ansible.builtin.shell:
    cmd: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list
- name: Install girlab-runner
  ansible.builtin.apt:
    name: "gitlab-runner={{ gitlab_runner_version }}"
    state: present
    update_cache: true
- name: Register gitlab-runner
  ansible.builtin.command:
    cmd: |
      gitlab-runner register \
        --non-interactive \
        --url "{{ gitlab_runner_url }}" \
        --token "{{ gitlab_runner_token }}" \
        --executor "{{ gitlab_runner_executor }}" \
        --description "aws-runner-{{ env }}" \
        --tag-list "{{ gitlab_runner_tags | join(',') }}"
    creates: /etc/gitlab-runner/config.toml
