#!/usr/bin/env bash

set -e

function help() {
	cat <<EOF
Usage:
  $(basename "$0") <command>

Commands:
  help          Shows this help message
  create        Create backend
  destroy       Destroy backend
EOF
}

function create() {
	if [[ -z "${TF_VAR_owner_id}" || -z "${AWS_PROFILE}" ]]; then
		if [[ -z "${TF_VAR_owner_id}" ]]; then
			echo "ERROR: TF_VAR_owner_id is not set"
		else
			echo "ERROR: AWS_PROFILE is not set"
		fi
		help
		exit 1
	fi

	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	cd "$SCRIPT_DIR/../terraform/bootstrap" || exit 2

	terraform init
	terraform apply
}

if [[ "$1" == "help" ]]; then
	help
elif [[ "$1" == "create" ]]; then
	create
elif [[ "$1" == "destroy" ]]; then
	echo "INFO: This operation is not allowed. Admin has to do it manually."
else
	echo "ERROR: Unkown command."
	help
	exit 1
fi
exit 0
