#!/usr/bin/env bash

set -e

function help() {
	cat <<EOF
Usage:
  $(basename "$0") <command>

Commands:
  help          Shows this help message
  install       Install gitlab-runner
  destroy       Destroy gitlab-runner
EOF
}

function install() {
	if [[ -z "${TF_VAR_owner_id}" || -z "${AWS_PROFILE}" ]]; then
		if [[ -z "${TF_VAR_owner_id}" ]]; then
			echo "ERROR: TF_VAR_owner_id is not set"
		else
			echo "ERROR: AWS_PROFILE is not set"
		fi
		help
		exit 1
	fi

	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	cd "$SCRIPT_DIR/../terraform/environment/dev/gitlab-runner" || exit 2

	read -p -r "Runner name: " runner_name
	export TF_VAR_runner_name=${runner_name}

	terraform init -reconfigure \
		-backend-config="bucket=tasky-terraform-state-${TF_VAR_owner_id}-dev" \
		-backend-config="key=runner/dev/$$runner_name/terraform.tfstate" &&
		terraform apply || exit 3

	cd "$SCRIPT_DIR/../ansible/environment/dev/gitlab-runner" || exit 2

	ansible-galaxy collection install -r requirements.yaml -p ./collections
	read -p -r "Runner token: " runner_token

	ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbook.yaml \
		-i inventory/aws_ec2.yaml \
		-l "runner_dev_${runner_name}" \
		-e runner_name="${runner_name}" \
		-e runner_token="${runner_token}" \
		-e owner_id="${TF_VAR_owner_id}" -vvvv
}

if [[ "$1" == "help" ]]; then
	help
elif [[ "$1" == "install" ]]; then
	install
elif [[ "$1" == "destroy" ]]; then
	echo "INFO: This operation is not allowed. Admin has to do it manually."
else
	echo "ERROR: Unkown command."
	help
	exit 1
fi
exit 0
