#!/usr/bin/env bash

set -euo pipefail

function help() {
	cat <<EOF
Usage:
  $(basename "$0") <command>

Commands:
  help          Shows this help message
  install       Install gitlab-runner
  update        Update gitlab-runner
  destroy       Destroy gitlab-runner
EOF
}

function prepare_operations() {
	if [[ -z "${TF_VAR_owner_id:-}" || -z "${AWS_PROFILE:-}" ]]; then
		if [[ -z "${TF_VAR_owner_id:-}" ]]; then
			echo "ERROR: TF_VAR_owner_id is not set"
		else
			echo "ERROR: AWS_PROFILE is not set"
		fi
		help && exit 1
	fi

	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	cd "$SCRIPT_DIR/../terraform/environment/dev/gitlab-runner" || exit 2
}

function install() {
	prepare_operations

	read -rp "Runner name: " runner_name
	export TF_VAR_runner_name=${runner_name}

	read -rp "Runner token: " runner_token

	read -rp "Availability zone: " availability_zone
	export TF_VAR_availability_zone=${availability_zone}

	terraform init -reconfigure \
		-backend-config="bucket=tasky-tf-state-${TF_VAR_owner_id}-dev" \
		-backend-config="key=runner/${availability_zone}/${runner_name}/terraform.tfstate"
	terraform apply -var-file=../default.tfvars -var-file=terraform.tfvars || exit 3

	cd "$SCRIPT_DIR/../ansible/environment/dev/gitlab-runner" || exit 4

	ansible-galaxy collection install -r requirements.yaml -p ./collections

	ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbook.yaml \
		-i inventory/aws_ec2.yaml \
		-l "runner_dev_${runner_name}" \
		-e runner_name="${runner_name}" \
		-e availability_zone="${availability_zone}" \
		-e runner_token="${runner_token}" \
		-e owner_id="${TF_VAR_owner_id}"
}

function update() {
	prepare_operations

	read -rp "Runner name: " runner_name
	export TF_VAR_runner_name=${runner_name}

	read -rp "Availability zone: " availability_zone
	export TF_VAR_availability_zone=${availability_zone}

	terraform init -reconfigure \
		-backend-config="bucket=tasky-tf-state-${TF_VAR_owner_id}-dev" \
		-backend-config="key=runner/${availability_zone}/${runner_name}/terraform.tfstate"
	terraform apply -var-file=../default.tfvars -var-file=terraform.tfvars || exit 3
}

function destroy() {
	prepare_operations

	read -rp "Runner name: " runner_name
	export TF_VAR_runner_name=${runner_name}

	read -rp "Availability zone: " availability_zone
	export TF_VAR_availability_zone=${availability_zone}

	terraform init -reconfigure \
		-backend-config="bucket=tasky-tf-state-${TF_VAR_owner_id}-dev" \
		-backend-config="key=runner/${availability_zone}/${runner_name}/terraform.tfstate"
	terraform destroy --auto-approve \
		-var-file=../default.tfvars -var-file=terraform.tfvars ||
		exit 3
}

if [[ "$1" == "help" ]]; then
	help
elif [[ "$1" == "install" ]]; then
	install
elif [[ "$1" == "update" ]]; then
	update
elif [[ "$1" == "destroy" ]]; then
	destroy
else
	echo "ERROR: Unkown command."
	help && exit 1
fi
exit 0
