- name: Install gitlab-runner dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: true
- name: Added gitlab-runner repo
  ansible.builtin.shell:
    cmd: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list
- name: Install gitlab-runner
  ansible.builtin.apt:
    name: "gitlab-runner={{ gitlab_runner_version }}"
    state: present
    update_cache: true
- name: Register gitlab-runner
  ansible.builtin.shell:
    cmd: |
      gitlab-runner register \
        --url "https://gitlab.com" \
        --token "{{ gitlab_runner_token }}" \
        --executor "docker" \
        --docker-image "alpine:latest" \
        --name "{{ gitlab_runner_name }}" \
        --non-interactive
    creates: /etc/gitlab-runner/config.toml
- name: Verify gitlab-runner is running
  ansible.builtin.systemd:
    name: gitlab-runner
    state: started
    enabled: true
