- name: Configure gitlab-runner
  hosts: gitlab_runner
  gather_facts: false
  pre_tasks:
    - name: Test SSM connection
      ansible.builtin.ping:
    - name: Gather facts
      ansible.builtin.setup:
  roles:
    - gitlab_runner
