plugin: amazon.aws.aws_ec2
aws_profile: tasky-dev
regions:
  - "eu-central-1"
filters:
  tag:Project: "tasky"
  tag:Role: gitlab-runner
  tag:Environment: dev
compose:
  ansible_host: instance_id
keyed_groups:
  - key: tags.RunnerName
    prefix: ""
    separator: ""
